spring:
  application:
    name: MiniAmazon_Backend
  datasource:
    url: jdbc:postgresql://localhost:5432/MiniAmazon
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
#    url: jdbc:h2:mem:mydb
#    username: root
#    password: root
#    driverClassName: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    username: exampleemail@gmail.com
    password: mypassword
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable=true
demo:
  db:
    name:
      mailfrom: exampleemail@gmail.com
server:
  port: 8082